project_id = "dogtizjeuhvqkrevxlew"

[functions.seed-admin]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false

[functions.get-users-with-email]
verify_jwt = false

[functions.summarize-evolutions]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
